name: Check Ferry Tickets

on:
  schedule:
    - cron: '*/15 * * * *'  # ⏰ 24시간 내내 15분마다 실행
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python check_ferry.py
